services:
  carbot:
    build:
      context: ./Carbot.web
      dockerfile: Dockerfile
    env_file:
      - ./Carbot.web/.env
    ports:
      - "5000:5000"
    volumes:
      - ./carbot-data:/app/data